# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ddadc6c5b4583fdfb793a771a19227d3c0deb60e7b86fbdb7d4cbeffe39515803cb5b85e5696756b763d1e76949ba8b9a17578704cd4d6efe29345fb786909

test:
  secret_key_base: a871d7df546b8abe2f1d5f0e8381f69acef9ace0d80b5342d6b58c8befec99c23aaf7e39911e93641393972571a9b7ea35ed300b69be0d6b7f0279b4d34136c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
